#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (c) 2026 Jacob Bühler
#
# What it takes to talk to a running e2e stack. Sourced by
# tests/e2e/docker/index-fulltextsearch.sh and by
# tests/e2e/docker/test-fulltextsearch.sh, so the env file, the compose
# project and the "is Elasticsearch up" check are worded once.
#
# Callers set "here" first, then source this file and name the variables
# they read:
#
#   source "$here/stack-env.sh"
#   require_stack_env E2E_USER

env_file="$here/../.env.e2e.docker"

if [[ ! -f "$env_file" ]]; then
	echo "$env_file is missing; run FULLTEXTSEARCH=1 NC_VERSION=34 $here/up.sh first." >&2
	exit 1
fi

set -a
# Generated by up.sh and restricted to the throwaway test stack.
# shellcheck disable=SC1090
source "$env_file"
set +a

compose() { docker compose -f "$here/compose.yml" "$@"; }

require_stack_env() {
	local variable
	for variable in "$@"; do
		if [[ -z "${!variable:-}" ]]; then
			echo "$variable is missing from $env_file." >&2
			exit 1
		fi
	done
}

require_elasticsearch() {
	if ! compose ps --services --status running | grep -qx elasticsearch; then
		echo "Elasticsearch is not running; start a fresh NC 34 stack with FULLTEXTSEARCH=1." >&2
		exit 1
	fi
}
