#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (c) 2026 Jacob Bühler
#
# Focused integration check for the optional NC 34 full-text-search stack.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
env_file="$here/../.env.e2e.docker"
ca_file="$here/certs/ca.crt"

if [[ ! -f "$env_file" ]]; then
	echo "$env_file is missing; run FULLTEXTSEARCH=1 NC_VERSION=34 $here/up.sh first." >&2
	exit 1
fi

set -a
# Generated by up.sh and restricted to the throwaway test stack.
# shellcheck disable=SC1090
source "$env_file"
set +a

for variable in E2E_BASE_URL E2E_USER E2E_APP_PASSWORD E2E_ETHERPAD_URL E2E_ETHERPAD_API_KEY; do
	if [[ -z "${!variable:-}" ]]; then
		echo "$variable is missing from $env_file." >&2
		exit 1
	fi
done

compose() { docker compose -f "$here/compose.yml" "$@"; }
if ! compose ps --services --status running | grep -qx elasticsearch; then
	echo "Elasticsearch is not running." >&2
	exit 1
fi

tmp="$(mktemp -d)"
suffix="${GITHUB_RUN_ID:-local}-$$-$(date +%s)"
suffix="${suffix//[^A-Za-z0-9-]/-}"
file_name="e2e-fulltextsearch-${suffix}.pad"
plain_marker="plainsearch${RANDOM}$(date +%s)"
html_marker="htmlonly${RANDOM}$(date +%s)"
created=0

urlencode() {
	python3 -c 'import sys, urllib.parse; print(urllib.parse.quote(sys.argv[1], safe=""))' "$1"
}

dav_url="$E2E_BASE_URL/remote.php/dav/files/$(urlencode "$E2E_USER")/$(urlencode "$file_name")"
trash_url="$E2E_BASE_URL/remote.php/dav/trashbin/$(urlencode "$E2E_USER")/trash"

cleanup() {
	set +e
	if [[ "$created" == 1 ]]; then
		curl --silent --show-error --cacert "$ca_file" \
			--user "$E2E_USER:$E2E_APP_PASSWORD" --request DELETE "$dav_url" >/dev/null
		curl --silent --show-error --cacert "$ca_file" \
			--user "$E2E_USER:$E2E_APP_PASSWORD" --request PROPFIND \
			--header 'Depth: 1' "$trash_url" > "$tmp/trash.xml"
		trash_entry="$(python3 - "$tmp/trash.xml" "$file_name" <<'PY'
import sys
import urllib.parse
import xml.etree.ElementTree as ET

root = ET.parse(sys.argv[1]).getroot()
prefix = sys.argv[2] + '.d'
for element in root.findall('.//{DAV:}href'):
    href = element.text or ''
    name = urllib.parse.unquote(href).rstrip('/').rsplit('/', 1)[-1]
    if name.startswith(prefix):
        print(href)
        break
PY
)"
		if [[ -n "$trash_entry" ]]; then
			curl --silent --show-error --cacert "$ca_file" \
				--user "$E2E_USER:$E2E_APP_PASSWORD" --request DELETE \
				"$E2E_BASE_URL$trash_entry" >/dev/null
		fi
		"$here/index-fulltextsearch.sh" >/dev/null
	fi
	rm -rf "$tmp"
}
trap cleanup EXIT

echo "==> creating $file_name"
created_json="$(curl --silent --show-error --fail-with-body --cacert "$ca_file" \
	--user "$E2E_USER:$E2E_APP_PASSWORD" --request POST \
	--header 'Accept: application/json' \
	--header 'OCS-APIRequest: true' \
	--data-urlencode "file=/$file_name" \
	--data-urlencode 'accessMode=public' \
	"$E2E_BASE_URL/index.php/apps/etherpad_nextcloud/api/v1/pads")"
created=1
printf '%s' "$created_json" > "$tmp/created.json"

file_id="$(python3 - "$tmp/created.json" <<'PY'
import json
import sys

data = json.load(open(sys.argv[1], encoding='utf-8'))
print(data['file_id'])
PY
)"
pad_id="$(python3 - "$tmp/created.json" <<'PY'
import json
import sys

data = json.load(open(sys.argv[1], encoding='utf-8'))
print(data['pad_id'])
PY
)"
if [[ ! "$file_id" =~ ^[1-9][0-9]*$ || ! "$pad_id" =~ ^nc-[a-z0-9]{24}$ ]]; then
	echo "Pad create response did not contain a valid file_id and pad_id: $created_json" >&2
	exit 1
fi
frontmatter_marker="${pad_id#nc-}"

echo "==> writing and synchronising the Etherpad content"
etherpad_json="$(curl --silent --show-error --fail-with-body --cacert "$ca_file" \
	--request POST \
	--data-urlencode "apikey=$E2E_ETHERPAD_API_KEY" \
	--data-urlencode "padID=$pad_id" \
	--data-urlencode "text=$plain_marker" \
	"$E2E_ETHERPAD_URL/api/1.2.15/setText")"
printf '%s' "$etherpad_json" > "$tmp/etherpad.json"
python3 - "$tmp/etherpad.json" <<'PY'
import json
import sys

data = json.load(open(sys.argv[1], encoding='utf-8'))
if data.get('code') != 0:
    raise SystemExit(f"Etherpad setText failed: {data}")
PY

curl --silent --show-error --fail-with-body --cacert "$ca_file" \
	--user "$E2E_USER:$E2E_APP_PASSWORD" --request POST \
	--header 'Accept: application/json' \
	--header 'OCS-APIRequest: true' \
	"$E2E_BASE_URL/index.php/apps/etherpad_nextcloud/api/v1/pads/sync/$file_id?force=1" \
	> "$tmp/sync.json"

# Make the HTML exclusion observable without changing the visible pad text.
curl --silent --show-error --fail-with-body --cacert "$ca_file" \
	--user "$E2E_USER:$E2E_APP_PASSWORD" "$dav_url" > "$tmp/pad"
python3 - "$tmp/pad" "$html_marker" <<'PY'
import sys

path, marker = sys.argv[1:]
content = open(path, encoding='utf-8').read()
needle = '\n[HTML-END]'
if content.count(needle) != 1:
    raise SystemExit('Synced pad did not contain exactly one HTML end marker.')
content = content.replace(needle, f'\n<!-- {marker} -->{needle}', 1)
open(path, 'w', encoding='utf-8').write(content)
PY
curl --silent --show-error --fail-with-body --cacert "$ca_file" \
	--user "$E2E_USER:$E2E_APP_PASSWORD" --request PUT \
	--header 'Content-Type: application/x-etherpad-nextcloud' \
	--data-binary "@$tmp/pad" "$dav_url" >/dev/null

echo "==> indexing and checking the search contract"
"$here/index-fulltextsearch.sh"
compose exec -T -u www-data nextcloud php occ fulltextsearch:search --output=json \
	"$E2E_USER" "$plain_marker" > "$tmp/plain.json"
compose exec -T -u www-data nextcloud php occ fulltextsearch:search --output=json \
	"$E2E_USER" "$html_marker" > "$tmp/html.json"
compose exec -T -u www-data nextcloud php occ fulltextsearch:search --output=json \
	"$E2E_USER" "$frontmatter_marker" > "$tmp/frontmatter.json"

python3 - "$tmp/plain.json" "$tmp/html.json" "$tmp/frontmatter.json" "$file_name" <<'PY'
import json
import sys

plain, html, frontmatter = [json.load(open(path, encoding='utf-8')) for path in sys.argv[1:4]]
file_name = sys.argv[4]
matches = [item for item in plain.get('files', []) if item.get('title') == file_name]
if len(matches) != 1:
    raise SystemExit(f'Expected exactly one plain-text result for {file_name}, got: {plain}')
icon = matches[0].get('info', {}).get('unified', {}).get('icon', '')
if 'etherpad-nextcloud-pad.svg' not in icon:
    raise SystemExit(f'Expected the pad icon, got: {icon!r}')
if any(item.get('title') == file_name for item in html.get('files', [])):
    raise SystemExit('The HTML-only marker was indexed.')
if any(item.get('title') == file_name for item in frontmatter.get('files', [])):
    raise SystemExit('The unique part of the frontmatter pad id was indexed.')
PY

echo "Full-text search found only the plain snapshot and returned the pad icon."
