#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (c) 2026 Jacob Bühler
#
# Bring up a throwaway Nextcloud + Etherpad target for the Playwright
# suite, seed it, and write tests/e2e/.env.e2e pointing at it.
#
#   NC_VERSION=32 tests/e2e/docker/up.sh
#
# Requires nc.pad.test and ep.pad.test to resolve to 127.0.0.1 — see
# tests/e2e/docker/README.md.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export NC_VERSION="${NC_VERSION:-33}"
# The Etherpad major. 2 is what the app is written against today; 3 moved
# the session cookie to the socket.io handshake and is what a run against
# it is meant to find out about.
export EP_VERSION="${EP_VERSION:-2}"

compose() { docker compose -f "$here/compose.yml" "$@"; }
# OC_PASS has to be forwarded explicitly: setting it on the host does
# nothing, `docker compose exec` only passes what -e names.
occ() { compose exec -T -u www-data -e OC_PASS="${OC_PASS:-}" nextcloud php occ "$@"; }

ADMIN_USER=admin
ADMIN_PASS=admin-e2e-pw
USER2=e2e-tester2
USER2_PASS=e2e-tester2-pw
API_KEY="$(tr -d '\n' < "$here/etherpad/APIKEY.txt")"

# up.sh promises a fresh installation, and Nextcloud refuses to upgrade
# across two majors — so pointing it at a volume from another NC_VERSION
# fails deep inside the container with nothing but "exited (1)" out here.
# Stop before that, and leave the decision to remove it to a person: a
# running stack is often the state someone is in the middle of examining.
if [[ -n "$(compose ps -aq 2>/dev/null)" ]]; then
	cat >&2 <<MSG
An existing e2e stack was found. Remove it with:

  docker compose -f tests/e2e/docker/compose.yml down -v --remove-orphans

For code changes in the running stack, use tests/e2e/docker/sync-app.sh instead.
MSG
	exit 1
fi

# Compose re-resolves ${NC_VERSION} and ${EP_VERSION} on every call, so a
# later `docker compose up` from a shell without them would decide the
# stack is out of date and recreate it on the defaults. Writing them where
# Compose looks by itself makes the choice a property of the stack rather
# than of whoever's shell brought it up.
echo "==> pinning the versions for later compose calls"
cat > "$here/.env" <<ENV
# Generated by tests/e2e/docker/up.sh — do not edit, it is overwritten.
NC_VERSION=$NC_VERSION
EP_VERSION=$EP_VERSION
ENV

echo "==> certificates"
bash "$here/make-certs.sh"

echo "==> starting the stack (Nextcloud ${NC_VERSION}, Etherpad ${EP_VERSION})"
compose up -d --build --wait

# `--wait` only honours the healthchecks; Nextcloud's own installer keeps
# running for a while after config.php appears.
echo "==> waiting for the Nextcloud installer"
installed=0
for _ in $(seq 1 90); do
	if occ status 2>/dev/null | grep -q 'installed: true'; then
		installed=1
		break
	fi
	sleep 2
done
if [[ "$installed" -ne 1 ]]; then
	echo "Nextcloud did not finish installing within three minutes. Container log:" >&2
	compose logs nextcloud --no-color --tail=30 >&2
	exit 1
fi
occ status | sed 's/^/    /'

echo "==> seeding"
occ app:disable firstrunwizard >/dev/null 2>&1 || true
occ config:system:set skeletondirectory --value=''
# Everything here lives on a private Docker network, which Nextcloud
# refuses to call into by default. Without this the base-URL reachability
# check warns — correctly, but about the sandbox rather than the app.
occ config:system:set allow_local_remote_servers --value=true --type=boolean

# No `|| true` swallow here: the stack is guaranteed fresh, so the user
# cannot already exist and any failure is a real one worth reading.
OC_PASS="$USER2_PASS" occ user:add --password-from-env --display-name="E2E Tester 2" "$USER2" >/dev/null

echo "==> installing the app"
bash "$here/sync-app.sh"

occ app:enable etherpad_nextcloud

# app:enable does not run the repair steps, so .pad stays an unknown
# extension and the Viewer never opens for it — which looks like a
# broken app rather than a missing setup step.
occ maintenance:repair >/dev/null
occ maintenance:mimetype:update-db >/dev/null
occ maintenance:mimetype:update-js >/dev/null

echo "==> configuring the app"
occ config:app:set etherpad_nextcloud etherpad_host --value='https://ep.pad.test'
# The API host stays internal http on purpose: it never leaves the Docker
# network, and it keeps pad traffic off the proxy.
occ config:app:set etherpad_nextcloud etherpad_api_host --value='http://etherpad:9001'
occ config:app:set etherpad_nextcloud etherpad_api_key --value="$API_KEY"
occ config:app:set etherpad_nextcloud etherpad_cookie_domain --value='pad.test'
occ config:app:set etherpad_nextcloud enable_protected_pads --value='yes'
occ config:app:set etherpad_nextcloud enable_public_pads --value='yes'
occ config:app:set etherpad_nextcloud delete_on_trash --value='yes'

# Nextcloud's default, set explicitly because a spec depends on it: a link
# share with edit rights is refused outright when public upload is off,
# and the public-folder-share spec needs edit rights to compare a pad's
# real address rather than a read-only one.
occ config:app:set core shareapi_allow_public_upload --value='yes'

echo "==> app passwords"
app_password() {
	OC_PASS="$2" occ user:add-app-password "$1" --password-from-env \
		| grep -oE '[A-Za-z0-9]{29,}' | tail -1
}
# `|| true`: without it the grep inside app_password fails the pipeline,
# errexit kills the script here, and the message below never prints.
ADMIN_APP_PW="$(app_password "$ADMIN_USER" "$ADMIN_PASS" || true)"
USER2_APP_PW="$(app_password "$USER2" "$USER2_PASS" || true)"

if [[ -z "$ADMIN_APP_PW" || -z "$USER2_APP_PW" ]]; then
	echo "could not read an app password out of occ output" >&2
	exit 1
fi

# Deliberately not .env.e2e: that file points at whatever long-lived
# instance the maintainer uses, and clobbering it would be a nasty
# surprise. The suite picks this one up via E2E_ENV_FILE.
echo "==> writing tests/e2e/.env.e2e.docker"
cat > "$here/../.env.e2e.docker" <<ENV
# Generated by tests/e2e/docker/up.sh — do not edit, it is overwritten.
E2E_BASE_URL=https://nc.pad.test
# Every variable fixtures/env.ts reads has to be here, including the
# optional ones: loading this file overrides what it defines, so anything
# it leaves out keeps whatever the shell exported — an E2E_LOGIN_URL for
# a real instance would send the login there while the rest of the suite
# talks to the container.
E2E_LOGIN_URL=/login
E2E_USER=$ADMIN_USER
E2E_PASS=$ADMIN_PASS
E2E_APP_PASSWORD=$ADMIN_APP_PW
E2E_USER2=$USER2
E2E_USER2_PASS=$USER2_PASS
E2E_USER2_APP_PASSWORD=$USER2_APP_PW
E2E_EXTERNAL_PADS=0
# Read by playwright.config.ts rather than fixtures/env.ts: the browser
# has no reason to trust a CA minted for this stack. NODE_EXTRA_CA_CERTS
# cannot live here — node reads it at startup, before dotenv runs — so
# run-suite.sh remains the entry point for this target.
E2E_IGNORE_HTTPS_ERRORS=1
ENV

# Guard against that drifting: a variable added to env.ts but not here
# would silently fall back to the shell's value.
expected=()
while IFS= read -r var; do
	expected+=("$var")
done < <(grep -hoE 'E2E_[A-Z_0-9]+' "$here/../fixtures/env.ts" "$here/../playwright.config.ts" \
	| grep -v '^E2E_ENV_FILE$' | sort -u)

# Fail closed: an empty list would mean the sources moved or were
# refactored, and an empty loop would report success while every variable
# quietly fell back to the shell.
if [[ "${#expected[@]}" -eq 0 ]]; then
	echo "Found no E2E_* variables to check for — did fixtures/env.ts or playwright.config.ts move?" >&2
	exit 1
fi

missing=""
for var in "${expected[@]}"; do
	grep -qE "^${var}=" "$here/../.env.e2e.docker" || missing="$missing $var"
done
if [[ -n "$missing" ]]; then
	echo "The suite reads variables this file does not set:$missing" >&2
	exit 1
fi

echo
echo "Nextcloud  https://nc.pad.test  ($ADMIN_USER / $ADMIN_PASS)"
echo "Etherpad   https://ep.pad.test  (major ${EP_VERSION})"
echo
echo "Run the suite against it with:"
echo "  tests/e2e/docker/run-suite.sh"
