#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (c) 2026 Jacob Bühler
#
# Bring up a throwaway Nextcloud + Etherpad target for the Playwright
# suite, seed it, and write tests/e2e/.env.e2e pointing at it.
#
#   NC_VERSION=32 tests/e2e/docker/up.sh
#
# Requires nc.pad.test and ep.pad.test to resolve to 127.0.0.1 — see
# tests/e2e/docker/README.md.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export NC_VERSION="${NC_VERSION:-33}"

compose() { docker compose -f "$here/compose.yml" "$@"; }
# OC_PASS has to be forwarded explicitly: setting it on the host does
# nothing, `docker compose exec` only passes what -e names.
occ() { compose exec -T -u www-data -e OC_PASS="${OC_PASS:-}" nextcloud php occ "$@"; }

ADMIN_USER=admin
ADMIN_PASS=admin-e2e-pw
USER2=e2e-tester2
USER2_PASS=e2e-tester2-pw
API_KEY="$(tr -d '\n' < "$here/etherpad/APIKEY.txt")"

echo "==> certificates"
bash "$here/make-certs.sh"

echo "==> starting the stack (Nextcloud ${NC_VERSION})"
compose up -d --build --wait

# `--wait` only honours the healthchecks; Nextcloud's own installer keeps
# running for a while after config.php appears.
echo "==> waiting for the Nextcloud installer"
for _ in $(seq 1 90); do
	if occ status 2>/dev/null | grep -q 'installed: true'; then
		break
	fi
	sleep 2
done
occ status | sed 's/^/    /'

echo "==> seeding"
occ app:disable firstrunwizard >/dev/null 2>&1 || true
occ config:system:set skeletondirectory --value=''
# Everything here lives on a private Docker network, which Nextcloud
# refuses to call into by default. Without this the base-URL reachability
# check warns — correctly, but about the sandbox rather than the app.
occ config:system:set allow_local_remote_servers --value=true --type=boolean

OC_PASS="$USER2_PASS" occ user:add --password-from-env --display-name="E2E Tester 2" "$USER2" >/dev/null 2>&1 \
	|| echo "    $USER2 already exists"

echo "==> installing the app"
bash "$here/sync-app.sh"

occ app:enable etherpad_nextcloud

# app:enable does not run the repair steps, so .pad stays an unknown
# extension and the Viewer never opens for it — which looks like a
# broken app rather than a missing setup step.
occ maintenance:repair >/dev/null
occ maintenance:mimetype:update-db >/dev/null
occ maintenance:mimetype:update-js >/dev/null

echo "==> configuring the app"
occ config:app:set etherpad_nextcloud etherpad_host --value='https://ep.pad.test'
# The API host stays internal http on purpose: it never leaves the Docker
# network, and it keeps pad traffic off the proxy.
occ config:app:set etherpad_nextcloud etherpad_api_host --value='http://etherpad:9001'
occ config:app:set etherpad_nextcloud etherpad_api_key --value="$API_KEY"
occ config:app:set etherpad_nextcloud etherpad_cookie_domain --value='pad.test'
occ config:app:set etherpad_nextcloud enable_protected_pads --value='yes'
occ config:app:set etherpad_nextcloud enable_public_pads --value='yes'
occ config:app:set etherpad_nextcloud delete_on_trash --value='yes'

echo "==> app passwords"
app_password() {
	OC_PASS="$2" occ user:add-app-password "$1" --password-from-env \
		| grep -oE '[A-Za-z0-9]{29,}' | tail -1
}
ADMIN_APP_PW="$(app_password "$ADMIN_USER" "$ADMIN_PASS")"
USER2_APP_PW="$(app_password "$USER2" "$USER2_PASS")"

if [[ -z "$ADMIN_APP_PW" || -z "$USER2_APP_PW" ]]; then
	echo "could not read an app password out of occ output" >&2
	exit 1
fi

# Deliberately not .env.e2e: that file points at whatever long-lived
# instance the maintainer uses, and clobbering it would be a nasty
# surprise. The suite picks this one up via E2E_ENV_FILE.
echo "==> writing tests/e2e/.env.e2e.docker"
cat > "$here/../.env.e2e.docker" <<ENV
# Generated by tests/e2e/docker/up.sh — do not edit, it is overwritten.
E2E_BASE_URL=https://nc.pad.test
E2E_USER=$ADMIN_USER
E2E_PASS=$ADMIN_PASS
E2E_APP_PASSWORD=$ADMIN_APP_PW
E2E_USER2=$USER2
E2E_USER2_PASS=$USER2_PASS
E2E_USER2_APP_PASSWORD=$USER2_APP_PW
E2E_EXTERNAL_PADS=0
ENV

echo
echo "Nextcloud  https://nc.pad.test  ($ADMIN_USER / $ADMIN_PASS)"
echo "Etherpad   https://ep.pad.test"
echo
echo "Run the suite against it with:"
echo "  tests/e2e/docker/run-suite.sh"
